services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the media folder to persist uploaded/processed images
      - media_volume:/app/mainserver/media
    env_file:
      - ./mainserver/.env
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  media_volume: