services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # This forces Docker to sync the container's media directly to your host's mainserver/media folder
      - ./mainserver/media:/app/mainserver/media
      - ./TrainedModelv3:/app/TrainedModelv3
    env_file:
      - ./mainserver/.env
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always